### ISSUE TITLE
Не создается файл для хранения задач 

### ISSUE THREAD

**Issue by ghost** [forkmalik/NCTaskManager#12]
Не создается файл для хранения задач при первом запуске программы.

Если создать пустой файл вручную то при запуске программы падает ошибка 

`Exception in thread "Thread-0" java.lang.NullPointerException
	at ua.edu.sumdu.j2se.savchenko.tasks.model.TaskIO.read(TaskIO.java:109)
	at ua.edu.sumdu.j2se.savchenko.tasks.model.TaskIO.readText(TaskIO.java:125)
	at ua.edu.sumdu.j2se.savchenko.tasks.controller.TaskController.readFile(TaskController.java:172)
	at ua.edu.sumdu.j2se.savchenko.tasks.controller.TaskController.startController(TaskController.java:189)
	at ua.edu.sumdu.j2se.savchenko.tasks.TaskThread.run(TaskThread.java:14)
`

**Comment by forkmalik** [comment]
Добавил создание файла при запуске и доработал оповещения, на случай если файл пустой

5bf13495420e4b6bd5282827e7b16f4bd4be1e0e
